### ISSUE TITLE
Dynamically change State-Transformations based on a Node's current State

### ISSUE THREAD

**Issue by AndreasFaust** [sghall/react-move#40]
Thanks for this awesome library! This is not an issue, rather I am looking for some advice, that I couldn't get from the docs.
I want to determine the State-Transformations in the Leave-Function based on the Nodes current State. In my concrete case I have a Full-Width-Slideshow, where the Slides come from the right and leave to the left side. But when the Enter-Animation is interrupted the incoming Slide should leave to the right side. 
Expressed in code:
```
    leave={data => (state.x <= 0
        ? data.transition.leave
        : data.transition.leaveReversed
    )}
```
I tried **setState** in the start-event of the leave function, where I can access the state, but it immediately gets overwritten.
Do you have any idea how to solve this without external state?

**Comment by sghall** [comment]
Hey there.  Hmmm...interesting question.  I think I understand what you mean.  Seems to me you have to store the information about whether to reverse the transition for that key higher up.  I don't think you can reliably get at that info in the enter/leave props. So maybe store the info in the component that contains the NodeGroup (I think you're using NodeGroup). 

Seem like if you know what keys are currently in the process of entering, you have all the info you need. You can fire functions on transition start and end.  Then just check that hash table (object) to see if it's currently entering.  The devil is in the details here, though.  You don't want to cause unnecessary renders that might cause the animations to jitter.  This is a bit tricky for sure.

There is no "update" scenario, right?  Keys enter and leave one at a time?

**Comment by AndreasFaust** [comment]
Thank you very much for the quick response. 
What I aim to do is a **routing transition**. As keys I use urls. So there is always just one active node entering and simultaneously the previous node leaving (and all the other previous nodes, which are still leaving, if you have an animation duration that is long enough). But if the entering is interrupted, I want the next (which now turns previous) page to leave the direction it came from, instead the normal leaving direction. I'll try it out, the way you described. If you like, I could give you some feedback. 
_Thanks again and have a nice weekend!_

**Comment by AndreasFaust** [comment]
Everything worked out just fine. Thank you!
