### ISSUE TITLE
React-Native animations

### ISSUE THREAD

**Issue by ekatzenstein** [sghall/react-move#61]
Use this library a lot for web projects (thank you for making!) — curious about the claims for react-native use — I'm assuming that animations are not run on the UI Thread (and instead run on the JS Thread).

If that is the case, the library isn't applicable to most mobile animations needs. Just a suggestion, since it was a little confusing when I used it on a react-native project.

**Comment by housseynCheriet** [comment]
Best explanation of easing function
https://www.selectionjs.com/animation
