### ISSUE TITLE
Peer dependency issue with npm 7

### ISSUE THREAD

**Issue by andtos90** [sghall/react-move#73]
### Problem or feature description
Using this package with npm v7 in a repository with Rect 17 will cause a peer dependency error. A suggested fix by @wildpow has been proposed in https://github.com/sghall/react-move/pull/71.

**Comment by samuelgoldenbaum** [comment]
Can we please get this merged in as it breaking dependencies down the line. Thanks.

**Comment by andtos90** [comment]
@sghall missed the notifications. He will take a look soon

**Comment by sghall** [comment]
The increased peer range was released in version `6.5.0` 👍  Please re-open this if you encounter any issues...
